language: python
python:
 - "3.9"

env:
  
  
services:
  - docker


branches:
 only:
 - commit
 
jobs:
  include:
    - stage : Build
      script:
      - sudo apt-get -y install ccrypt
      - ./travis_script/deploy/UI_Front_deploy.sh
	
