language: python
python:
 - "3.9"

env:
  
  
services:
  - docker


branches:
 only:
 - commit
 
 
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  
  
jobs:
  include:
    - stage : Build
      script:
      - sudo apt-get -y install ccrypt
      - cd travis_script
      - ./deploy.sh
      - cd ..
	
