language: python
python:
 -'3.9'

env:
  
  
services:
  - docker


branches:
 only:
 - commit
 
jobs:
  include:
    - stage : Build
      script:
      - ./travis_script/deploy/UI_Front_deploy.sh
	
